CREATE DATABASE IF NOT EXISTS proyectoDB;

USE proyectoDB;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  correo VARCHAR(100) NOT NULL UNIQUE,
  telefono VARCHAR(20),
  contrasena VARCHAR(255) NOT NULL,
  token_recuperacion VARCHAR(255) NULL,
  token_expiracion DATETIME NULL
);